<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StudentApplication extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'program',
        'group',
        'session',
        'sNameBangla',
        'sNameEnglish',
        'bloodGroup',
        'religion',
        'gender',
        'dob',
        'bitId',
        'nid',
        'nationality',
        'maritalStatus',
        'sMobileNo',
        'sPicture',
        'fName',
        'fNid',
        'fQualification',
        'fOccupation',
        'fMonthlyIncome',
        'fMobileNo',
        'mName',
        'mNid',
        'mQualification',
        'mOccupation',
        'mMonthlyIncome',
        'mMobileNo',
        'permanentAddressVil',
        'permanentAddressPO',
        'permanentAddressPS',
        'permanentAddressDist',
        'presentAddressVil',
        'presentAddressPO',
        'presentAddressPS',
        'presentAddressDist',
        'gName',
        'gNid',
        'gRelation',
        'gMobileNo',
        'gEmail',
        'gAddress',
        'refName',
        'refNid',
        'refRelation',
        'refMobileNo',
        'refEmail',
        'refAddress',
        'examName1',
        'rollNo1',
        'regNo1',
        'sessionExam1',
        'gpa1',
        'passingYear1',
        'Board1',
        'examName2',
        'rollNo2',
        'regNo2',
        'sessionExam2',
        'gpa2',
        'passingYear2',
        'Board2',
        'compulsory1',
        'compulsory2',
        'compulsory3',
        'elective1',
        'elective2',
        'elective3',
        'optional',
        'status',
        'hobby',
        'extracurriculam',
        'created_date',
        'pinCode',
    ];
    
    protected $casts = [
        'dob' => 'datetime',
        'created_date' => 'datetime',
        'gpa1' => 'float',
        'gpa2' => 'float',
        'bitId' => 'integer',
        'nid' => 'integer',
        'sMobileNo' => 'integer',
        'fNid' => 'integer',
        'fMonthlyIncome' => 'integer',
        'fMobileNo' => 'integer',
        'mNid' => 'integer',
        'mMonthlyIncome' => 'integer',
        'mMobileNo' => 'integer',
        'gNid' => 'integer',
        'gMobileNo' => 'integer',
        'refNid' => 'integer',
        'refMobileNo' => 'integer',
        'status' => 'integer',
    ];
}
